<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Password must be 5-40 characters long</name>
   <tag></tag>
   <elementGuidId>b3aa8f65-fcf7-4f9c-9688-0a5293d71a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-hint[@id='mat-hint-0']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>c4fc9213-2ab8-44bb-ae4c-28178a4652a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password must be 5-40 characters long.</value>
      <webElementGuid>97b5f872-86db-4548-96b1-d050f8f941cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-hint-0&quot;)/em[1]</value>
      <webElementGuid>d76e2213-f478-44d1-a661-070508c3168f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-hint[@id='mat-hint-0']/em</value>
      <webElementGuid>952cedb3-46e8-42ce-a7dd-9e4a8869a0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Password'])[1]/following::em[1]</value>
      <webElementGuid>577ffa59-7747-4014-9927-d366c0a616da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Question'])[1]/following::em[1]</value>
      <webElementGuid>c2ac0fc7-fad8-4fb8-a05f-2fdab0d5cbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat New Password'])[1]/preceding::em[1]</value>
      <webElementGuid>7a6cb8dd-6650-4128-a741-4ddd7174f71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password must be 5-40 characters long.']/parent::*</value>
      <webElementGuid>5c2a5165-bd1e-4a9a-ab13-2033c8f5b1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>2db7e780-d970-4d1c-b34a-92c50514ab92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Password must be 5-40 characters long.' or . = 'Password must be 5-40 characters long.')]</value>
      <webElementGuid>dea77e81-96dc-4721-8705-d73b0fccf537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
