<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat New Password</name>
   <tag></tag>
   <elementGuidId>d2cc06f7-1a09-4013-a1a6-7844a88390a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPasswordRepeat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPasswordRepeat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fe68e58-1fd0-4027-874f-46f002af2616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPasswordRepeat</value>
      <webElementGuid>a201e600-9586-4ec1-b6cb-664ddc0a5ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bfea7a46-7c50-452a-8be0-a4dab65f6dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field to confirm the new password</value>
      <webElementGuid>c64465b7-e14a-4853-b65b-71b06b2d3eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-10 ng-untouched ng-pristine cdk-text-field-autofill-monitored</value>
      <webElementGuid>beb695c7-58a9-4f01-bc44-8fca59941ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-hint-2</value>
      <webElementGuid>fccabad7-2691-4438-a237-f9ffa9f16589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2311b375-c3cf-419b-b07a-e897a1525ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPasswordRepeat&quot;)</value>
      <webElementGuid>adc31675-e567-4503-8062-56ca0d6618b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPasswordRepeat']</value>
      <webElementGuid>058b43df-785d-4c09-82c3-bedf75ae3086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>dda14876-aeec-4173-ae4d-02f6e2b7cc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>78ab086a-c8fe-4639-90e8-b921bc0996ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newPasswordRepeat' and @type = 'password']</value>
      <webElementGuid>00fa4e7e-f338-4b19-8d86-7d7d6b5567b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
