<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password</name>
   <tag></tag>
   <elementGuidId>5779c6d2-ca0d-4793-8c87-67e5522bf80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4814fc29-ae3b-41be-ac1b-090892083995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>4b3f8782-7a0d-4f71-b2b3-c6cca42fe20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>17e1764c-81fa-42b3-a3a6-241868ec6667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field for New Password</value>
      <webElementGuid>e7c11d56-a7c5-41aa-b335-003aecacacfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-9 ng-untouched ng-pristine cdk-text-field-autofill-monitored</value>
      <webElementGuid>0ae458f1-6098-4023-8cf2-e6008939a593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-hint-0 mat-hint-1</value>
      <webElementGuid>59f91d37-df68-498a-a3e5-4e9ca48bb2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc3ee9f5-97f2-4ade-ba85-9f6e149bf8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPassword&quot;)</value>
      <webElementGuid>e8090dcb-df59-4199-960f-8b053b76f7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPassword']</value>
      <webElementGuid>31ff1396-829c-4329-a208-de9a629e1c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>726bb209-61ef-4627-920d-984713893aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>2fd90ccf-3e2f-4e01-a8ec-bc7c870b3811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newPassword' and @type = 'password']</value>
      <webElementGuid>bfcb774e-4ace-4da7-8163-834cb27e26ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
