<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_error</name>
   <tag></tag>
   <elementGuidId>844eef6d-dfaa-47ce-bb45-bbd95c959460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>fcdc45a5-47e6-4a25-bd8e-381956ac810a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f98b652c-0077-4a8e-b2dd-4898691f5731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>37a4a4cb-f1b1-4013-8c93-06b600f92e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mat-warn ng-tns-c29-11 ng-trigger ng-trigger-negativeState material-icons mat-ligature-font ng-star-inserted</value>
      <webElementGuid>501bf3db-7c2e-4229-870e-5e4d19a690d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74fa0e4a-ab85-4273-8fdc-2d1439b38ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>d63fe6b5-365b-487c-9c7b-35e7218dfbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>1c9c7df5-c158-4fff-b67e-2e18ee924de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-form&quot;)/mat-password-strength-info[@class=&quot;ng-tns-c29-11 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c29-11 ng-trigger ng-trigger-list&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;info-row ng-tns-c29-11 ng-trigger ng-trigger-items ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-warn ng-tns-c29-11 ng-trigger ng-trigger-negativeState material-icons mat-ligature-font ng-star-inserted&quot;]</value>
      <webElementGuid>bbdaf660-3198-4cf8-89ea-1051aefb1324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div[2]/mat-icon</value>
      <webElementGuid>87f8df35-2940-4cd9-baf0-35d3a6069a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one lower character'])[1]/following::mat-icon[1]</value>
      <webElementGuid>17cc196c-fc3f-4968-81d1-e881758554dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one upper character'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>15fb224a-55a2-477d-956f-143b799c63f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one digit'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>d6c3766d-7697-4dce-9f6c-c19cbb009252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-icon</value>
      <webElementGuid>1a19d34c-3707-47e1-b15a-5cd3ddd1feed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'error' or . = 'error')]</value>
      <webElementGuid>f10af0ca-7988-4cc9-b4c5-ccfd8351698b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
