<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Done</name>
   <tag></tag>
   <elementGuidId>4ad628f3-67bc-4b05-8e98-a4450cef11e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-icon[@role = 'img' and @color = 'primary' and (text() = 'done' or . = 'done')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.mat-warn.ng-tns-c29-17.ng-trigger.ng-trigger-negativeState.material-icons.mat-ligature-font.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>48ecd53b-7ac7-4fed-bfe0-3227acdf4d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5162b488-ccb5-4cb0-a116-e207cb879c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>c2483e3b-225f-48aa-b8a6-a54ca27dd5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mat-warn ng-tns-c29-17 ng-trigger ng-trigger-negativeState material-icons mat-ligature-font ng-star-inserted</value>
      <webElementGuid>f9280af6-cd44-453f-a4f8-24a80e0b1bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51b404b8-6679-435d-9bec-970fd9bdeec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>e1913eb9-8395-4a89-8860-eee906fa2dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>done</value>
      <webElementGuid>a67f614b-f832-49d0-96ce-5d2afd411359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-form&quot;)/mat-password-strength-info[@class=&quot;ng-tns-c29-17 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c29-17 ng-trigger ng-trigger-list&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;info-row ng-tns-c29-17 ng-trigger ng-trigger-items ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-warn ng-tns-c29-17 ng-trigger ng-trigger-negativeState material-icons mat-ligature-font ng-star-inserted&quot;]</value>
      <webElementGuid>514d4fdd-d31b-4ff4-9d66-55cfe97fa970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/mat-icon</value>
      <webElementGuid>1304d384-0716-4650-ae1f-b1c55973ef0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please repeat your password.'])[1]/following::mat-icon[1]</value>
      <webElementGuid>810c88fe-4c63-43fb-ba43-0167f3df5448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one lower character'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>d906fc46-480f-4ba7-b11f-969a2f2ed104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one upper character'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>6f429827-2d0e-47f3-8056-a68c68377ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='error']/parent::*</value>
      <webElementGuid>725aa094-54ab-4fa9-8d77-74c0fa31650b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div/mat-icon</value>
      <webElementGuid>d1e9e9f5-b6a7-4851-a19b-78b33e2611eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'error' or . = 'error')]</value>
      <webElementGuid>3902d717-1e64-4a34-afe3-7912a025f1d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
