<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Already a customer</name>
   <tag></tag>
   <elementGuidId>a89be19f-b47a-46c0-9f63-130334667f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alreadyACustomerLink']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3df37b9d-35fd-4b86-85b7-0deb89205f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>5d2da556-4796-41ac-a750-29f5ddeb9fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link</value>
      <webElementGuid>8d5eb51f-a9b8-4bc2-b91f-47c06811ebd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/login</value>
      <webElementGuid>2d1c5eb2-42c3-4d0e-aeec-0ac35417f384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Already a customer?</value>
      <webElementGuid>3c82bf35-5189-41ca-99a9-3651e20d0c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alreadyACustomerLink&quot;)/a[@class=&quot;primary-link&quot;]</value>
      <webElementGuid>13df1d7d-46c7-4c9c-aa6c-b5a500d8ac08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alreadyACustomerLink']/a</value>
      <webElementGuid>c3d05059-a64d-4d8b-b478-784e62d6f72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Already a customer?')]</value>
      <webElementGuid>58b5b837-edae-4c4a-9589-2080117fcbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person_add'])[1]/following::a[1]</value>
      <webElementGuid>1c9204ec-ae84-49a9-80bd-a24e0b0bb60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open side menu'])[1]/preceding::a[1]</value>
      <webElementGuid>c19b258b-9810-4cf9-a51d-85564e82c0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose language'])[1]/preceding::a[1]</value>
      <webElementGuid>98714f64-1c77-4756-8d94-c24cd821fb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Already a customer?']/parent::*</value>
      <webElementGuid>5896d93b-66f4-4326-9787-f6c19728bd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/login')])[2]</value>
      <webElementGuid>bee1b390-8e2e-4486-b755-d9ecde8cdd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>175a0482-13f2-4bd1-8627-cfeda4b6129b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/login' and (text() = 'Already a customer?' or . = 'Already a customer?')]</value>
      <webElementGuid>8600f1ea-c61f-4c47-a174-907918498f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
