<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security Answer</name>
   <tag></tag>
   <elementGuidId>fd560aa6-08ee-4587-bbaf-b036f10cd04d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#securityAnswerControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAnswerControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>417637a8-7fa5-45de-8c15-10ddafae40fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAnswerControl</value>
      <webElementGuid>ca276d7a-2514-4202-b1bd-923b9a599df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cf566a9-cdec-413b-864b-a658f905d70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field for the answer to the security question</value>
      <webElementGuid>577541d2-d6b8-4af4-acb1-23f6d99aad3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-12 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>96d75399-2e7e-4664-ad0d-6039f5967537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>5727c6e8-9c74-48f5-ad28-9b641a2e0587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86c5ba36-9d3e-43a5-9514-6acdb59aab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>0fe3bc71-5e04-4518-8af3-77d220f9d8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAnswerControl&quot;)</value>
      <webElementGuid>4d64edd4-9afd-4f1a-82fd-4a395a90bea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAnswerControl']</value>
      <webElementGuid>b0f3396f-a90e-4d8a-8b34-3397b9ac2e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>d544a29a-7e05-4daa-b4a5-8a5501549284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>85109301-855d-463c-a280-dd858fe27a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'securityAnswerControl' and @type = 'text' and @placeholder = 'Answer to your security question']</value>
      <webElementGuid>7da37868-79e5-452d-87da-c2fbe0924eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
