<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contains at least one upper character</name>
   <tag></tag>
   <elementGuidId>2f1efd8b-5507-406d-9983-c773508a61b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'contains at least one upper character' or . = 'contains at least one upper character')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a52cfc3-91c6-4f83-80bd-9aa8b171e9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c29-11</value>
      <webElementGuid>1369dbf9-9ba7-4a58-b655-162c58a0e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contains at least one upper character</value>
      <webElementGuid>c4a95e99-fa32-4b7b-8b10-682b2c169cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-form&quot;)/mat-password-strength-info[@class=&quot;ng-tns-c29-11 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c29-11 ng-trigger ng-trigger-list&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;info-row ng-tns-c29-11 ng-trigger ng-trigger-items ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c29-11&quot;]</value>
      <webElementGuid>cf5e10e4-2dd1-4118-a374-3b529730f334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div[2]/span</value>
      <webElementGuid>18ee80e3-8bf3-4422-adf9-fc2a41103163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one lower character'])[1]/following::span[1]</value>
      <webElementGuid>c4273a9b-83d9-45a3-b979-5ac5dd3f1ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one digit'])[1]/preceding::span[1]</value>
      <webElementGuid>0459af94-fb7c-446d-8529-996c26d8581c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one special character'])[1]/preceding::span[2]</value>
      <webElementGuid>1d332ee6-4b57-4e70-87b3-e5705ec57248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='contains at least one upper character']/parent::*</value>
      <webElementGuid>5be4c83a-3af3-47ba-9713-9a65317d107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div[2]/span</value>
      <webElementGuid>ea53e127-c76d-4c72-9908-0049ff7aec49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'contains at least one upper character' or . = 'contains at least one upper character')]</value>
      <webElementGuid>4a6976e6-6b8a-4908-b553-35778013f014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
