<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contains at least one lower character</name>
   <tag></tag>
   <elementGuidId>f8f90d05-ee4e-4f59-ad81-c0192ad783b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'contains at least one lower character' or . = 'contains at least one lower character')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c29-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9edfcda0-26cc-4071-908f-51e11ab43333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c29-11</value>
      <webElementGuid>d9611756-086b-4b8f-8246-799d9333f1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contains at least one lower character</value>
      <webElementGuid>60acd58b-1224-432c-935e-71127340da96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-form&quot;)/mat-password-strength-info[@class=&quot;ng-tns-c29-11 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c29-11 ng-trigger ng-trigger-list&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;info-row ng-tns-c29-11 ng-trigger ng-trigger-items ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c29-11&quot;]</value>
      <webElementGuid>2239c847-5aee-4b3d-ab78-f340b55e6079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/span</value>
      <webElementGuid>3c469414-e47b-47a0-b3e0-55261fbd07c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat New Password'])[1]/following::span[8]</value>
      <webElementGuid>711b92a0-a319-4018-8e6f-1961faf8ca3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one upper character'])[1]/preceding::span[1]</value>
      <webElementGuid>7563121b-f86a-481a-b164-deadf219b51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one digit'])[1]/preceding::span[2]</value>
      <webElementGuid>b382651b-6811-4215-8eda-16eafede55ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='contains at least one lower character']/parent::*</value>
      <webElementGuid>9c1fb2be-41a9-422f-8e04-552ed7248f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div/span</value>
      <webElementGuid>7328e463-2e29-4580-8af5-31ed1e30dcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'contains at least one lower character' or . = 'contains at least one lower character')]</value>
      <webElementGuid>935db308-24ed-4f63-8237-fe6b683d7211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
