<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add a coupon code to receive discounts_coupon</name>
   <tag></tag>
   <elementGuidId>62059d6d-beb3-47f9-8298-ecc8c00a9f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'coupon' and @type = 'text' and @placeholder = 'Please enter your coupon code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0d0e9f9-cedb-4e26-a702-8b0e2b3bb9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon</value>
      <webElementGuid>4f3bdb1d-0750-4b62-aac2-62d1240c8875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a4ba957-1c45-484d-a6bd-e2e1078e6c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-15 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>a02e2fc3-58eb-4fbc-9978-dca4ae25cc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your coupon code</value>
      <webElementGuid>1e59cb3a-c598-4bc0-928c-f0dca0ace6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-hint-1 mat-hint-2</value>
      <webElementGuid>d959830f-2fb6-41d7-bd0e-72f9be2112c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Please enter your coupon code</value>
      <webElementGuid>8e1e730f-5dd1-45a3-b220-f24ec5c1b32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce1ef5c7-9771-43f9-a36b-0d5a2f733896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon&quot;)</value>
      <webElementGuid>222b165b-1caf-4598-ac6e-956b96908f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon']</value>
      <webElementGuid>1261faf1-8881-42d2-b7e9-e7dbd531c307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>3c401ec7-c8f7-416f-93ad-dc24459e4456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel/div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>c2f7774c-938f-49e5-b78b-e421f76115aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coupon' and @type = 'text' and @placeholder = 'Please enter your coupon code']</value>
      <webElementGuid>f2629150-1cce-42b4-ac67-8fe946812507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
