<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-hint_Need a coupon code</name>
   <tag></tag>
   <elementGuidId>3ca84cb9-e703-4774-8297-7e3c1287df77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-hint-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-hint[@id='mat-hint-1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-hint[(text() = 'Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!' or . = 'Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-hint</value>
      <webElementGuid>79dabfe8-8fff-4b86-b948-fd0d405484c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-hint ng-tns-c21-15</value>
      <webElementGuid>d0ce67ad-3e9f-4d12-a55c-b5a97763e655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-hint-1</value>
      <webElementGuid>80145890-06f0-4902-86d9-9d375f32daf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!</value>
      <webElementGuid>f17b75c5-a7b3-408a-a60d-34db800ccb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-hint-1&quot;)</value>
      <webElementGuid>4f0fe7ca-36e6-4a31-98b2-3798e3c9ca42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-hint[@id='mat-hint-1']</value>
      <webElementGuid>841e1ad8-abda-4d3e-b4e0-a7e03165f6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/mat-form-field/div/div[2]/div/mat-hint</value>
      <webElementGuid>285aa987-1adc-475f-86a9-9e9b2d9f01a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon'])[1]/following::mat-hint[1]</value>
      <webElementGuid>46699dbc-423c-4049-97a3-535152c80e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a coupon code to receive discounts'])[1]/following::mat-hint[1]</value>
      <webElementGuid>165ca682-a381-406c-8cc4-364bd21d76f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Need a coupon code? Follow us on']/parent::*</value>
      <webElementGuid>019c5537-e166-4ca4-9dec-d5bf4def48b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel/div/div/mat-form-field/div/div[2]/div/mat-hint</value>
      <webElementGuid>efe6dbb3-d107-4836-a790-43e35b113bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-hint[@id = 'mat-hint-1' and (text() = 'Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!' or . = 'Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!')]</value>
      <webElementGuid>284ea384-bbeb-46ed-8804-bbebf3a8eae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
