<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add a credit or debit card</name>
   <tag></tag>
   <elementGuidId>c0803189-b920-444e-8ace-2006038dbe9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-expansion-indicator.ng-tns-c41-8.ng-trigger.ng-trigger-indicatorRotate.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-0']/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mat-expansion-indicator ng-tns-c41-8 ng-trigger ng-trigger-indicatorRotate ng-star-inserted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbf3bde3-15c1-41f4-a543-ca0b705f8bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-indicator ng-tns-c41-8 ng-trigger ng-trigger-indicatorRotate ng-star-inserted</value>
      <webElementGuid>e1a684ef-af0c-48ff-94a8-ccee04ae69de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-0&quot;)/span[@class=&quot;mat-expansion-indicator ng-tns-c41-8 ng-trigger ng-trigger-indicatorRotate ng-star-inserted&quot;]</value>
      <webElementGuid>a9067baa-6abd-4145-aae4-8e0ec9830427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-0']/span[2]</value>
      <webElementGuid>1cffc76a-9da4-419c-96f2-03b8b5a15f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header/span[2]</value>
      <webElementGuid>6326c5b4-0417-4e43-b25a-ad760a1d6fe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
