<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OpenSea</name>
   <tag></tag>
   <elementGuidId>273b34b4-2b76-439d-a012-672516465946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5) > button.mat-focus-indicator.mat-stroked-button.mat-button-base > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-2']/div/div/div[2]/div[2]/a[5]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mat-button-wrapper' and (text() = ' OpenSea' or . = ' OpenSea')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0543f16-08aa-4811-91ce-0f21f32578ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>da149297-7185-4c90-9155-7ca48ef61dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OpenSea</value>
      <webElementGuid>f5b52264-08c2-482b-a8bc-07834fc48b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c40-16&quot;]/div[@class=&quot;ng-tns-c40-16&quot;]/div[@class=&quot;mat-elevation-z0&quot;]/div[@class=&quot;button-container&quot;]/a[5]/button[@class=&quot;mat-focus-indicator mat-stroked-button mat-button-base&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>739f3cdc-00e4-40f4-9b38-fa32d8241908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div[2]/div[2]/a[5]/button/span</value>
      <webElementGuid>538290e9-9371-47f4-9bfa-99bf5a5b4502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leanpub'])[1]/following::span[3]</value>
      <webElementGuid>67ede7d8-bf2b-4c89-be21-78b669cf0721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StickerYou'])[1]/following::span[6]</value>
      <webElementGuid>cc08f810-4292-48eb-8696-add3688bf2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::span[6]</value>
      <webElementGuid>51f1d678-445a-4015-a8a9-8a85d86f1813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OpenSea']/parent::*</value>
      <webElementGuid>1192919c-5547-41b3-a4da-d02e7d323625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/button/span</value>
      <webElementGuid>52a12c9e-fbf9-4161-838e-bc3969b036c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' OpenSea' or . = ' OpenSea')]</value>
      <webElementGuid>407f3c30-f394-419d-b2c9-ee59fe28bac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
