<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Redeem</name>
   <tag></tag>
   <elementGuidId>d34afa5a-0957-45bb-bf7e-30f72d56ab81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applyCouponButton > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='applyCouponButton']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mat-button-wrapper' and (text() = ' Redeem ' or . = ' Redeem ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9c0de11-b741-4587-8689-5da331c3d76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>3ab67cd6-de7c-4f0d-8077-c718c3ed03a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Redeem </value>
      <webElementGuid>c257e873-a908-46e8-8c8e-8febf6605b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyCouponButton&quot;)/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>011c903a-dd1f-4d15-b8b9-5cfadaf51bbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='applyCouponButton']/span</value>
      <webElementGuid>8a56675c-4fdd-4cea-bd41-14590f3f680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::span[1]</value>
      <webElementGuid>c007e716-3c1a-4e46-830d-adc06079fd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/following::span[1]</value>
      <webElementGuid>b59c7919-f479-4bbd-9ea7-4bf233c661a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other payment options'])[1]/preceding::span[3]</value>
      <webElementGuid>01e51f9a-8e78-489d-b194-57cf8f01c6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donations'])[1]/preceding::span[5]</value>
      <webElementGuid>3233d1c0-027c-4efe-9328-707041ec56a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Redeem']/parent::*</value>
      <webElementGuid>24eb3d1f-e84b-4f58-a89d-552ffee64e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-expansion-panel/div/div/button/span</value>
      <webElementGuid>97ef1016-2480-4be1-afbb-f0857f9059c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' redeem  Redeem ' or . = ' redeem  Redeem ')]</value>
      <webElementGuid>20257995-2a1d-4236-a851-724644e22876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
