<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Leanpub</name>
   <tag></tag>
   <elementGuidId>731c762c-b64f-4b1f-8aec-949965868f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(4) > button.mat-focus-indicator.mat-stroked-button.mat-button-base > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-2']/div/div/div[2]/div[2]/a[4]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mat-button-wrapper' and (text() = ' Leanpub' or . = ' Leanpub')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>86effac1-4397-42da-93b4-090acecc8f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>695c3843-536f-4e91-b49e-dc729138a11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Leanpub</value>
      <webElementGuid>13d24774-5cd7-471f-86cf-81a7dc9f6e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c40-16&quot;]/div[@class=&quot;ng-tns-c40-16&quot;]/div[@class=&quot;mat-elevation-z0&quot;]/div[@class=&quot;button-container&quot;]/a[4]/button[@class=&quot;mat-focus-indicator mat-stroked-button mat-button-base&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>790020fd-6c10-4afb-8f10-deb1bd7dc5df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div[2]/div[2]/a[4]/button/span</value>
      <webElementGuid>c436f96b-381f-4584-8d7c-3dec4101b79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StickerYou'])[1]/following::span[3]</value>
      <webElementGuid>63c68baf-d581-4fa9-b617-f47428e0d14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spreadshirt (DE)'])[1]/following::span[6]</value>
      <webElementGuid>254863b9-5d35-43eb-b9cd-162f66486c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OpenSea'])[1]/preceding::span[3]</value>
      <webElementGuid>2cc526f2-11d7-45d6-963e-448ddf3a1567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leanpub']/parent::*</value>
      <webElementGuid>91c43141-6f1d-4bd4-9171-c2cfd8f78bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/button/span</value>
      <webElementGuid>abb7f4eb-e132-4f4b-b60c-d83c72aa8bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Leanpub' or . = ' Leanpub')]</value>
      <webElementGuid>25a7478f-6056-4a9d-bf28-564e5051a148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
