<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>0024ff8a-df7d-4861-a450-20792d6282ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbarLogoutButton > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbarLogoutButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfbcff05-565b-4a6f-a997-dc14db3bc0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Logout </value>
      <webElementGuid>60d598ed-029e-47e6-afee-2d25da119a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarLogoutButton&quot;)/span[1]</value>
      <webElementGuid>80fffdfa-51f4-47d6-9138-3814561f4dc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='navbarLogoutButton']/span</value>
      <webElementGuid>53adc793-5a99-458b-9d58-84aa46f1674a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; Security'])[2]/following::span[1]</value>
      <webElementGuid>23b301eb-3ac8-4c96-8fed-903b50f7d581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders &amp; Payment'])[2]/following::span[2]</value>
      <webElementGuid>ef717521-4af0-4ac0-b9ee-53cf91115f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open side menu'])[1]/preceding::span[1]</value>
      <webElementGuid>e74cc275-6e3c-403f-a721-44f7fa0eceeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose language'])[1]/preceding::span[1]</value>
      <webElementGuid>18b82320-7e33-432b-8791-0bc052dceb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[4]/span</value>
      <webElementGuid>0c6d877f-1644-4c9c-88d5-d07f6fa69f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Logout ' or . = ' Logout ')]</value>
      <webElementGuid>8b30e921-6e94-45df-962d-34e8f438a644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
