<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search Value</name>
   <tag></tag>
   <elementGuidId>6459417d-58fe-4397-ad36-2cf66fda21c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='searchValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adfed7ba-b973-43a5-8bea-9fe22d359a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchValue</value>
      <webElementGuid>8fec4596-7f72-4af7-b1df-59cd1913a96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple Juice (1000ml)</value>
      <webElementGuid>6efc6bfe-9740-4708-9814-3732d24cae63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchValue&quot;)</value>
      <webElementGuid>8a777660-bc9b-4031-aec0-d9d2594e776b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='searchValue']</value>
      <webElementGuid>62f00146-1d85-4142-8b41-bb854b9b7a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results -'])[1]/following::span[1]</value>
      <webElementGuid>6b7fa0c3-7ef4-4032-8e11-cc6497b4529a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::span[4]</value>
      <webElementGuid>25456030-0227-424a-916e-2b4bf130f0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Juice (1000ml)'])[2]/preceding::span[1]</value>
      <webElementGuid>e908511f-9741-4b3f-859a-f65163a4c1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::span[2]</value>
      <webElementGuid>f72ff7ec-de5c-432f-bde2-76d4f78e79dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apple Juice (1000ml)']/parent::*</value>
      <webElementGuid>2c932b25-b9b9-49d2-b804-ecdbda046957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>e6889623-5edf-4ad8-bf15-a07af335f038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'searchValue' and (text() = 'Apple Juice (1000ml)' or . = 'Apple Juice (1000ml)')]</value>
      <webElementGuid>9dde0067-f76a-4303-8f21-4c47d61a5348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
