<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Please repeat your password</name>
   <tag></tag>
   <elementGuidId>2ab9a119-aad5-4d07-a42a-a7ba83eac06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-error-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-22']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[(text() = ' Please repeat your password. ' or . = ' Please repeat your password. ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>64378983-d6af-46ca-93c5-b3242d089b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edd26433-6a47-49b9-b45a-cc42fc721f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c21-15 ng-star-inserted</value>
      <webElementGuid>eefa0c14-644d-4cbe-b139-419e4f17418e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1d261eaa-394c-4c5b-984f-1fa4adc905e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-22</value>
      <webElementGuid>e3ee6c3c-a627-4c20-804c-83a704ad58b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please repeat your password. </value>
      <webElementGuid>2d8a3883-4152-4ebd-9547-66529960b3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-22&quot;)</value>
      <webElementGuid>553c8880-5441-40c9-879a-5924f38d0f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-22']</value>
      <webElementGuid>76f4de84-fa49-4fef-baef-bcb53e9e7c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/mat-form-field[3]/div/div[2]/div/mat-error</value>
      <webElementGuid>b966588d-6270-4867-b40c-81f35fb93f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat Password'])[1]/following::mat-error[1]</value>
      <webElementGuid>f9bab94f-dea9-49db-b69f-36f9727ce209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide a password.'])[1]/following::mat-error[1]</value>
      <webElementGuid>a8722359-8c42-409c-a7d3-a9d15c2226ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Mother', &quot;'&quot;, 's maiden name?')])[1]/preceding::mat-error[1]</value>
      <webElementGuid>bb6975db-6d5f-4912-ac06-09ab65dabd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please repeat your password.']/parent::*</value>
      <webElementGuid>ed56eee3-9836-453a-9137-47fc1e3d5c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div[2]/div/mat-error</value>
      <webElementGuid>c52a90b4-7cdb-4c83-815c-86311e64448f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-22' and (text() = ' Please repeat your password. ' or . = ' Please repeat your password. ')]</value>
      <webElementGuid>cb0e9dac-2b8e-4521-854a-15a7dc9cdfb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
