<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>67c8e618-ff41-44f4-90e0-d493347ed5b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@routerlink = '/forgot-password' and @href = '#/forgot-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.primary-link.forgot-pw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c676d8ce-fe6b-490d-b990-b3251ef0a134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/forgot-password</value>
      <webElementGuid>2148399e-0584-48bd-a9d1-730356a3d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link forgot-pw</value>
      <webElementGuid>abf56f56-331e-4c1f-95d4-30c25558b8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/forgot-password</value>
      <webElementGuid>3a80c28c-d67f-4344-9ba7-e0cad714e945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>6bc4b9b9-cc00-4ae2-a804-c40138030729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/a[@class=&quot;primary-link forgot-pw&quot;]</value>
      <webElementGuid>a236cfc8-e437-4c95-9115-01e0b8edc394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/a</value>
      <webElementGuid>de818906-f5ad-47d3-a2d0-15e972449793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>7404b7be-10d4-4396-abaf-28b8c71d135a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>928463ec-fac0-438e-b41c-43aaf1c1845b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::a[1]</value>
      <webElementGuid>e19a0245-cdeb-4f8b-af8a-72b6cc1f932a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>2960bb5e-0d07-4842-b720-c21be360a52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/forgot-password')]</value>
      <webElementGuid>ad44231a-bfc9-487c-9ad1-c691a39be4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/a</value>
      <webElementGuid>161a7deb-b8e7-4c2d-bf99-b2d2af3d6fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/forgot-password' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>66376c28-9f2d-402a-a61b-9e8224d2d30e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
