<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_done</name>
   <tag></tag>
   <elementGuidId>3a544b17-2435-49f3-a822-6ab3df5c4840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.mat-primary.ng-tns-c29-17.ng-trigger.ng-trigger-positiveState.material-icons.mat-ligature-font.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>bc700928-5c81-4661-8df9-9c9108e5b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c3388dd-8df9-42e7-b447-86161ec91351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>26464a76-9713-4a82-9bb7-74003b164418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mat-primary ng-tns-c29-17 ng-trigger ng-trigger-positiveState material-icons mat-ligature-font ng-star-inserted</value>
      <webElementGuid>eefa834c-d06b-4366-89c0-870b887288df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84bc9aa5-ea5b-495f-b974-eefdd2fa60b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>38d14ecc-471f-4588-ae9e-b14066d45dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>done</value>
      <webElementGuid>87e1a1a6-6907-429d-aaa6-ef04756a6cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-form&quot;)/mat-password-strength-info[@class=&quot;ng-tns-c29-17 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c29-17 ng-trigger ng-trigger-list&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;info-row ng-tns-c29-17 ng-trigger ng-trigger-items ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-primary ng-tns-c29-17 ng-trigger ng-trigger-positiveState material-icons mat-ligature-font ng-star-inserted&quot;]</value>
      <webElementGuid>c936cb98-94e1-4c8e-95b4-f81809b6549d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgot-form']/mat-password-strength-info/mat-card/mat-card-content/div/mat-icon</value>
      <webElementGuid>4bb16fe5-a097-48ec-b752-52d6b5e2964a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passwords do not match'])[1]/following::mat-icon[1]</value>
      <webElementGuid>c5fdfd08-a1e6-4aad-a5d2-3b6ff9f26053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one lower character'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>1d60271e-42f2-4dec-b1ce-4115559a3f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contains at least one upper character'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>32b34714-bfbe-44c1-b8b7-0d12478f5f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='done']/parent::*</value>
      <webElementGuid>df328d24-0a39-4abc-8ab0-e01c2d88a4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div/mat-icon</value>
      <webElementGuid>e0865730-830b-4ec5-a726-176341dd9a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'done' or . = 'done')]</value>
      <webElementGuid>c71cb143-ea77-4cb4-8a3b-bd56bd9a7416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
