<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_Captcha</name>
   <tag></tag>
   <elementGuidId>2ce6e661-591d-47d3-b921-47b3d96388ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//code[@id = 'captcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#captcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//code[@id='captcha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>f9d22f47-85ab-47dd-b149-61848e1472d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>bb9d7884-8a36-4d2c-a70f-0c2c0331c138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>CAPTCHA code which must be solved</value>
      <webElementGuid>fa4bdfe9-d3d9-4748-b92d-dbb45c22dfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8-3-7</value>
      <webElementGuid>7a4c0d1b-2791-4035-b15d-449c9cb0aadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha&quot;)</value>
      <webElementGuid>748b8858-f524-421f-8b36-236533a51273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//code[@id='captcha']</value>
      <webElementGuid>5cb0d7b7-b5b3-4dd6-8eb0-60cc42e7897f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedback-form']/div[2]/code</value>
      <webElementGuid>18249e75-782e-48b3-8ba6-e29a0093ac34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is'])[1]/following::code[1]</value>
      <webElementGuid>09b77da3-721d-4faa-8c85-7be128228b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAPTCHA:'])[1]/following::code[1]</value>
      <webElementGuid>545ee93f-119e-46fe-99e2-db17ad4f19e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/preceding::code[1]</value>
      <webElementGuid>c7623622-8354-4a1c-a6a7-a87c637a1606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result'])[1]/preceding::code[1]</value>
      <webElementGuid>fa40cec9-e5a7-426e-baf4-e4df2b6342ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8-3-7']/parent::*</value>
      <webElementGuid>75c9db41-5aae-4484-b59d-09af4dc5b3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code</value>
      <webElementGuid>7c13c3ab-6d81-4db0-9f23-5f7dc4c2bafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//code[@id = 'captcha' and (text() = '8-3-7' or . = '8-3-7')]</value>
      <webElementGuid>4eab716c-2a7b-4e14-8e05-e7396c8630c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
