<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-slider_Rating Slider</name>
   <tag></tag>
   <elementGuidId>e915af00-c128-4af4-8833-5450d59f0504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'rating' and (text() = '0★' or . = '0★')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-slider[@id='rating']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-slider</value>
      <webElementGuid>9c42dbb9-2ea5-49b3-85bc-2a0c81676938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>aa0b969e-1254-4886-9729-b62cbd15dbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rating</value>
      <webElementGuid>6b72e718-1756-403c-8e0d-e416b62648fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>88384533-a930-47da-b1a9-c8cadbc042da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>996bad44-50a7-42e8-9c95-03c8a9eb8b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tickinterval</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e44203ad-564a-48ae-8195-e66411a4d9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Slider for selecting the star rating</value>
      <webElementGuid>ca9a1776-4787-4e0d-b5e2-1aca158d4ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-slider mat-focus-indicator mat-accent mat-slider-has-ticks mat-slider-horizontal mat-slider-thumb-label-showing mat-slider-min-value</value>
      <webElementGuid>e9672d95-b7d5-49a2-97cf-98a06eda89f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f218bed-55f7-4dfe-bf49-c11751553bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>42744d9d-ed33-4958-be8c-67a511f8236e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f1f2fe76-29d7-4480-92b9-9ba61e6dd769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b5f9bce1-0f4f-4e7a-9d58-5686e59fd857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>731fda5b-268c-4c3d-94d4-d1294f84fe1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuetext</name>
      <type>Main</type>
      <value>0★</value>
      <webElementGuid>12d70c9e-8e59-4dff-8664-155a620584b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>a916e0ee-1a03-4453-beb9-462a66ac42e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0★</value>
      <webElementGuid>e1536000-c61a-4a1f-81da-6a9c038a1e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rating&quot;)</value>
      <webElementGuid>906d261c-a348-470e-8f2e-8a911eeaa2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-slider[@id='rating']</value>
      <webElementGuid>e2649f71-12ab-4dc8-acb9-4e390ab812b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedback-form']/div/mat-slider</value>
      <webElementGuid>bb03eae0-dc0f-4c65-b96c-d12b5d08e138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[1]/following::mat-slider[1]</value>
      <webElementGuid>d4c5daff-40d9-4030-a672-60419b2cfb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max. 160 characters'])[1]/following::mat-slider[1]</value>
      <webElementGuid>d63c7a26-a02a-4057-b5bd-d32da3b7adeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAPTCHA:'])[1]/preceding::mat-slider[1]</value>
      <webElementGuid>335515aa-3a6f-451a-b65a-ac7e32e6cd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is'])[1]/preceding::mat-slider[1]</value>
      <webElementGuid>e8bfd843-6c7d-4b9c-b89b-ea3de96b76fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-slider</value>
      <webElementGuid>bfe92578-286e-44a9-9895-c81b37c850b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-slider[@id = 'rating' and (text() = '0★' or . = '0★')]</value>
      <webElementGuid>6c59010f-619d-4fdc-b766-279f816fd8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
